### ISSUE TITLE
Directory isn't created

### ISSUE THREAD

**Issue by Astro165** [macster9/GalaxyClassifier#2]
Hi

I tried to run the code but I get the following error in the main code:
FileNotFoundError: [Errno 2] No such file or directory: 'data/train'

I can see: train, test and validate aren't created in the data folder. I tried looking at the code named data_pipeline, but it seems to run fin, so I can't find the problem.

**Comment by macster9** [comment]
Try manually creating those folders and see if this rectifies the issue.

When I get the opportunity I will create the functionality to create these
folders correctly.

Many thanks,
Ted

**Comment by Astro165** [comment]
If I do this i just get the error message:
FileNotFoundError: [Errno 2] No such file or directory: 'models/model_396326'

and if I manually create a folder in models the error message just keep coming but with different numbers i.e:
FileNotFoundError: [Errno 2] No such file or directory: 'models/model_XXXXXX'

**Comment by Astro165** [comment]
Hi again

I found a way to create the directory but know I encounter a new problem. The code needs an errors.txt file and a labels.cvs file. I can create these manually but this means the two files are empty. This leads to a new error "KeyError: 'IMG_ID'" which means the code can't find the needed information in this case labels.cvs file. I think the same problem will appear for the errors.txt file. 

Do you know how I create these files correctly so they contain the right information?

Thank you in advance for your help

**Comment by macster9** [comment]
Just pushing those files now and added a few lines in the readme which should help. It's been a while since I let this project go so I need to sit down and comb through it properly so that it's functional when running from scratch.

Am happy to sit down over a teams call to demo this project on my machine and talk about it further (but am UK based so timezoning may be an issue).

Otherwise, sit tight and I will get back to this to fix as soon as I can.

**Comment by macster9** [comment]
^ worth mentioning I have only done this on the improved_labels branch

**Comment by macster9** [comment]
I have also added the files to main. Here are the instructions you can find in the improved_labels branch:
1. Create the following directories if they don't already exist:
   1. data/
   2. models/
2. In addition, go to find the original data used https://www.kaggle.com/datasets/jaimetrickz/galaxy-zoo-2-images
3. Unzip those images to the data/images/ directory and run the data_pipeline.split_datasets() function. This should sort the images into the train/test/validate folders.
   1. **note:** if those 3 directories are not created, you can manually create them in the data/ directory (just 3 folders called train/test/validate respectively). These directories will need to be empty and run only once.
 
This is all going to be temporary as I plan to come back and fix this repo.

**Comment by macster9** [comment]
I have pushed some changes to main to get this to work in a jupyter notebook.
Clone down from main, run the batch files (__install__.bat and run.bat) to install the virtual environment, install dependencies, and open jupyter. Navigate to notebooks/Execut.ipynb and see instructions here to run everything.

I am now closing this issue, please raise another if this is persistent or there is anything else I can do to help/explain.
